import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Icons } from "@/components/Icons";
import { Header } from "@/components/Header";

const manrope = localFont({
  src: "./fonts/Manrope-VariableFont_wght.woff2",
  variable: "--font-manrope",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased`}>
        <Icons />
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
